export const ACCESS_TOKEN_KEY = "destinai_access_token";

export const CP_PLATFORMS = [
  { key: "leetcode",   label: "LeetCode",    placeholder: "your_handle",   icon: "terminal"       },
  { key: "codeforces", label: "Codeforces",  placeholder: "your_handle",   icon: "military_tech"  },
  { key: "codechef",   label: "CodeChef",    placeholder: "your_handle",   icon: "restaurant"     },
  { key: "gfg",        label: "GeeksForGeeks",placeholder: "your_handle",  icon: "school"         },
  { key: "hackerrank", label: "HackerRank",  placeholder: "your_handle",   icon: "code"           },
] as const;

export const TARGET_ROLES = [
  // Software Engineering
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "React Developer",
  "Angular Developer",
  "Vue Developer",
  "Android Developer",
  "iOS Developer",
  "Flutter Developer",
  "React Native Developer",
  // AI & ML
  "AI Engineer",
  "Machine Learning Engineer",
  "Deep Learning Engineer",
  "Generative AI Engineer",
  "LLM Engineer",
  "Prompt Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "AI Research Engineer",
  "MLOps Engineer",
  // Data
  "Data Scientist",
  "Data Analyst",
  "Business Analyst",
  "Analytics Engineer",
  "Data Engineer",
  "BI Developer",
  // Cloud & Infrastructure
  "Cloud Engineer",
  "DevOps Engineer",
  "Platform Engineer",
  "Site Reliability Engineer",
  "Infrastructure Engineer",
  // Security
  "Cyber Security Engineer",
  "SOC Analyst",
  "Ethical Hacker",
  "Application Security Engineer",
  "Penetration Tester",
  // Specialized
  "Blockchain Developer",
  "Embedded Engineer",
  "IoT Engineer",
  "Automation Engineer",
  "QA Engineer",
  "Test Automation Engineer",
  "Game Developer",
  "AR/VR Developer",
  // Architecture & Consulting
  "Solutions Architect",
  "Product Engineer",
  "Technical Consultant",
  "Technical Lead",
  "Engineering Manager",
  // Additional specialized roles (CHANGE 7)
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  "Go Developer",
  "Rust Developer",
  "C++ Developer",
  "Ruby Developer",
  "PHP Developer",
  "Scala Developer",
  "TypeScript Developer",
  "Web Developer",
  "Mobile Developer",
  "Database Engineer",
  "Big Data Engineer",
  "BI Engineer",
  "Network Engineer",
  "Hardware Engineer",
  "Research Scientist",
  "Product Manager",
  "Scrum Master",
  "CTO",
] as const;

export const EXPERIENCE_LEVELS = [
  { value: "0-1", label: "0-1 (Junior)"    },
  { value: "1-3", label: "1-3 (Associate)" },
  { value: "3-5", label: "3-5 (Mid)"       },
  { value: "5-8", label: "5-8 (Senior)"    },
  { value: "8+",  label: "8+ (Staff/Lead)" },
] as const;
